import type { Scenario } from './types';

export const cafe: Record<string, Scenario> = {
	en: {
		id: 'cafe',
		name: 'Café',
		icon: '☕',
		description: 'Brewer, fridge, lights — the shop tells its day',
		story: 'Brewer warming up, customers trickling in, quiet afternoon...',
		accent: 'rgba(217,169,99,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '05:30', actor: 'Barista' },
			{ type: 'session.start', timestamp: '05:45', device: 'Coffee machine' },
			{ type: 'routine.hit', timestamp: '06:00', actor: 'Shop' },
			{ type: 'threshold.crossed', timestamp: '08:30', zone: 'Storefront', severity: 'normal' },
			{ type: 'anomaly', timestamp: '10:15', zone: 'Brewer', severity: 'warning' },
			{ type: 'recovery', timestamp: '10:25', zone: 'Brewer' },
			{ type: 'session.end', timestamp: '14:00', device: 'Coffee machine', duration_min: 495 },
			{ type: 'presence.left', timestamp: '14:30', actor: 'Barista' },
		],
		interpreter: {
			name: 'Café',
			tone: 'calm',
			map: {
				'presence.arrived': '{actor} opened up the shop',
				'presence.left': '{actor} closed for the day',
				'session.start': '{device} warming up — ready to brew',
				'session.end': '{device} off — ran for {duration_min} minutes',
				anomaly: '⚠ {zone} acting up',
				recovery: '{zone} back to normal',
				'routine.hit': '{actor} opened right on time',
				'routine.missed': '{actor} running late today',
				'cycle.complete': '{device} cleaned — {duration_min} minutes',
				'threshold.crossed': '{zone} getting crowded',
			},
		},
	},
	th: {
		id: 'cafe',
		name: 'ร้านกาแฟ',
		icon: '☕',
		description: 'เครื่องชง ตู้เย็น ไฟ — ร้านเล่าวันของมัน',
		story: 'เครื่องชงอุ่นตัว ลูกค้าทยอยมา ช่วงบ่ายร้านเงียบ…',
		accent: 'rgba(217,169,99,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '05:30', actor: 'บาริสต้า' },
			{ type: 'session.start', timestamp: '05:45', device: 'เครื่องชงกาแฟ' },
			{ type: 'routine.hit', timestamp: '06:00', actor: 'ร้าน' },
			{ type: 'threshold.crossed', timestamp: '08:30', zone: 'หน้าร้าน', severity: 'normal' },
			{ type: 'anomaly', timestamp: '10:15', zone: 'เครื่องชง', severity: 'warning' },
			{ type: 'recovery', timestamp: '10:25', zone: 'เครื่องชง' },
			{ type: 'session.end', timestamp: '14:00', device: 'เครื่องชงกาแฟ', duration_min: 495 },
			{ type: 'presence.left', timestamp: '14:30', actor: 'บาริสต้า' },
		],
		interpreter: {
			name: 'ร้านกาแฟ',
			tone: 'calm',
			map: {
				'presence.arrived': '{actor} มาเปิดร้านแล้ว',
				'presence.left': '{actor} ปิดร้านแล้ว',
				'session.start': '{device} อุ่นเครื่องพร้อมชง',
				'session.end': '{device} ปิดแล้ว · ทำงานมา {duration_min} นาที',
				anomaly: '⚠ {zone} มีอาการผิดปกติ',
				recovery: '{zone} กลับมาปกติแล้ว',
				'routine.hit': '{actor} เปิดตรงเวลาเหมือนทุกวัน',
				'routine.missed': '{actor} เปิดสายวันนี้',
				'cycle.complete': '{device} ล้างเสร็จแล้ว · {duration_min} นาที',
				'threshold.crossed': '{zone} ลูกค้าเริ่มแน่น',
			},
		},
	},
};
