import type { Scenario } from './types';

export const car: Record<string, Scenario> = {
	en: {
		id: 'car',
		name: 'Autonomous Car',
		icon: '🚗',
		description: 'Passengers, routes, obstacles — the vehicle reports its journey',
		story: 'Passenger boarded, route calculated, obstacle detected mid-trip...',
		accent: 'rgba(251,191,36,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '08:00', actor: 'Passenger' },
			{ type: 'session.start', timestamp: '08:01', device: 'Navigation' },
			{ type: 'routine.hit', timestamp: '08:02', actor: 'Self-check system' },
			{ type: 'anomaly', timestamp: '08:25', zone: 'Forward sensor', severity: 'warning' },
			{ type: 'recovery', timestamp: '08:26', zone: 'Forward sensor' },
			{ type: 'threshold.crossed', timestamp: '08:40', zone: 'Battery', severity: 'warning' },
			{ type: 'session.end', timestamp: '08:55', device: 'Navigation', duration_min: 54 },
			{ type: 'presence.left', timestamp: '08:56', actor: 'Passenger' },
		],
		interpreter: {
			name: 'Vehicle Control',
			tone: 'mission',
			map: {
				'presence.arrived': 'Passenger entered vehicle — trip started',
				'presence.left': 'Passenger exited — trip complete',
				'session.start': '{device} system engaged',
				'session.end': '{device} disengaged — {duration_min} min trip',
				anomaly: '⚠ {zone} — obstacle detected',
				recovery: '{zone} — clear',
				'routine.hit': '{actor} — all systems nominal',
				'routine.missed': '{actor} — check overdue',
				'cycle.complete': '{device} route complete — {duration_min} min',
				'threshold.crossed': '{zone} level low',
			},
		},
	},
	th: {
		id: 'car',
		name: 'รถอัตโนมัติ',
		icon: '🚗',
		description: 'ผู้โดยสาร เส้นทาง สิ่งกีดขวาง — รถรายงานการเดินทาง',
		story: 'ผู้โดยสารขึ้นรถ คำนวณเส้นทาง ตรวจพบสิ่งกีดขวางระหว่างทาง…',
		accent: 'rgba(251,191,36,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '08:00', actor: 'ผู้โดยสาร' },
			{ type: 'session.start', timestamp: '08:01', device: 'ระบบนำทาง' },
			{ type: 'routine.hit', timestamp: '08:02', actor: 'ระบบตรวจสอบ' },
			{ type: 'anomaly', timestamp: '08:25', zone: 'เซ็นเซอร์ด้านหน้า', severity: 'warning' },
			{ type: 'recovery', timestamp: '08:26', zone: 'เซ็นเซอร์ด้านหน้า' },
			{ type: 'threshold.crossed', timestamp: '08:40', zone: 'แบตเตอรี่', severity: 'warning' },
			{ type: 'session.end', timestamp: '08:55', device: 'ระบบนำทาง', duration_min: 54 },
			{ type: 'presence.left', timestamp: '08:56', actor: 'ผู้โดยสาร' },
		],
		interpreter: {
			name: 'ระบบควบคุมรถ',
			tone: 'mission',
			map: {
				'presence.arrived': 'ผู้โดยสารขึ้นรถ — เริ่มเดินทาง',
				'presence.left': 'ผู้โดยสารลงรถ — จบการเดินทาง',
				'session.start': '{device} เริ่มทำงาน',
				'session.end': '{device} ปิดระบบ — {duration_min} นาที',
				anomaly: '⚠ {zone} — ตรวจพบสิ่งกีดขวาง',
				recovery: '{zone} — ปลอดภัย',
				'routine.hit': '{actor} — ระบบปกติ',
				'routine.missed': '{actor} — เลยกำหนดตรวจสอบ',
				'cycle.complete': '{device} เสร็จสิ้นเส้นทาง — {duration_min} นาที',
				'threshold.crossed': '{zone} ระดับต่ำ',
			},
		},
	},
};
