import type { Scenario } from './types';

export const home: Record<string, Scenario> = {
	en: {
		id: 'home',
		name: 'Home',
		icon: '🏠',
		description: 'Electricity tells who did what, and when',
		story: "Dad left early, Mom hasn't returned, something odd in the kitchen...",
		accent: 'rgba(34,197,94,1)',
		events: [
			{ type: 'session.start', timestamp: '06:32', device: 'Kettle' },
			{ type: 'session.end', timestamp: '06:44', device: 'Kettle', duration_min: 12 },
			{ type: 'presence.left', timestamp: '07:15', actor: 'Dad' },
			{ type: 'session.start', timestamp: '08:40', device: 'Living room TV' },
			{ type: 'anomaly', timestamp: '09:02', zone: 'Kitchen', severity: 'warning' },
			{ type: 'recovery', timestamp: '09:10', zone: 'Kitchen' },
			{ type: 'session.end', timestamp: '09:45', device: 'Living room TV', duration_min: 65 },
			{ type: 'presence.arrived', timestamp: '10:20', actor: 'Mom' },
		],
		interpreter: {
			name: 'Home',
			tone: 'warm',
			map: {
				'presence.arrived': 'Welcome back, {actor}! Late one today.',
				'presence.left': '{actor} headed out — gate closed behind them',
				'session.start': '{device} switched on',
				'session.end': '{device} off — was on for {duration_min} minutes',
				anomaly: 'Hmm, something unusual in {zone}...',
				recovery: 'All clear in {zone} now',
				'routine.hit': '{actor} right on schedule',
				'routine.missed': "{actor} hasn't done their morning routine",
				'cycle.complete': '{device} finished — {duration_min} minutes',
				'threshold.crossed': '{zone} crossed the threshold',
			},
		},
	},
	th: {
		id: 'home',
		name: 'บ้าน',
		icon: '🏠',
		description: 'ไฟฟ้าเล่าว่าใครทำอะไร เมื่อไหร่',
		story: 'พ่อออกไปก่อน แม่ยังไม่กลับ มีอะไรบางอย่างในครัว…',
		accent: 'rgba(34,197,94,1)',
		events: [
			{ type: 'session.start', timestamp: '06:32', device: 'กาต้มน้ำ' },
			{ type: 'session.end', timestamp: '06:44', device: 'กาต้มน้ำ', duration_min: 12 },
			{ type: 'presence.left', timestamp: '07:15', actor: 'พ่อ' },
			{ type: 'session.start', timestamp: '08:40', device: 'ทีวีห้องนั่งเล่น' },
			{ type: 'anomaly', timestamp: '09:02', zone: 'ห้องครัว', severity: 'warning' },
			{ type: 'recovery', timestamp: '09:10', zone: 'ห้องครัว' },
			{ type: 'session.end', timestamp: '09:45', device: 'ทีวีห้องนั่งเล่น', duration_min: 65 },
			{ type: 'presence.arrived', timestamp: '10:20', actor: 'แม่' },
		],
		interpreter: {
			name: 'บ้าน',
			tone: 'warm',
			map: {
				'presence.arrived': '{actor} กลับบ้านแล้ว',
				'presence.left': '{actor} ออกจากบ้านแล้ว',
				'session.start': '{device} เริ่มทำงาน',
				'session.end': '{device} ปิดแล้ว · {duration_min} นาที',
				anomaly: '⚠ มีการใช้ไฟที่ไม่รู้จัก · {zone}',
				recovery: 'กลับสู่ปกติแล้ว · {zone}',
				'routine.hit': '{actor} ทำกิจวัตรตามปกติ',
				'routine.missed': '{actor} ยังไม่ทำกิจวัตรเช้า',
				'cycle.complete': '{device} เสร็จแล้ว · {duration_min} นาที',
				'threshold.crossed': '{zone} เกินเกณฑ์แล้ว',
			},
		},
	},
};
