import type { Scenario } from './types';

export const humanoid: Record<string, Scenario> = {
	en: {
		id: 'humanoid',
		name: 'Humanoid',
		icon: '🤖',
		description: 'Operator, servos, task queue — the robot reports its shift',
		story: 'Operator arrived, servos calibrated, task queue running, a joint jammed...',
		accent: 'rgba(244,114,182,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '07:00', actor: 'Operator' },
			{ type: 'routine.hit', timestamp: '07:05', actor: 'Servo calibration' },
			{ type: 'session.start', timestamp: '07:10', device: 'Task queue' },
			{ type: 'cycle.complete', timestamp: '09:00', device: 'Assembly arm', duration_min: 110 },
			{ type: 'anomaly', timestamp: '10:30', zone: 'Joint 3', severity: 'warning' },
			{ type: 'recovery', timestamp: '10:35', zone: 'Joint 3' },
			{ type: 'session.end', timestamp: '12:00', device: 'Task queue', duration_min: 290 },
			{ type: 'presence.left', timestamp: '12:05', actor: 'Operator' },
		],
		interpreter: {
			name: 'Robot Control',
			tone: 'industrial',
			map: {
				'presence.arrived': '{actor} returned to station — resuming task queue',
				'presence.left': '{actor} disconnected — standby mode',
				'session.start': '{device} initiated',
				'session.end': '{device} completed — {duration_min} min runtime',
				anomaly: '⚠ {zone} — fault detected',
				recovery: '{zone} — recalibrated',
				'routine.hit': '{actor} — diagnostics passed',
				'routine.missed': '{actor} — diagnostics overdue',
				'cycle.complete': '{device} — batch done · {duration_min} min',
				'threshold.crossed': '{zone} — wear threshold reached',
			},
		},
	},
	th: {
		id: 'humanoid',
		name: 'หุ่นยนต์',
		icon: '🤖',
		description: 'ผู้ควบคุม เซอร์โว คิวงาน — หุ่นยนต์รายงานกะงาน',
		story: 'ผู้ควบคุมมาถึง เซอร์โวปรับตั้ง คิวงานทำงาน ข้อต่อติด…',
		accent: 'rgba(244,114,182,1)',
		events: [
			{ type: 'presence.arrived', timestamp: '07:00', actor: 'ผู้ควบคุม' },
			{ type: 'routine.hit', timestamp: '07:05', actor: 'ระบบปรับเซอร์โว' },
			{ type: 'session.start', timestamp: '07:10', device: 'คิวงาน' },
			{ type: 'cycle.complete', timestamp: '09:00', device: 'แขนประกอบ', duration_min: 110 },
			{ type: 'anomaly', timestamp: '10:30', zone: 'ข้อต่อ 3', severity: 'warning' },
			{ type: 'recovery', timestamp: '10:35', zone: 'ข้อต่อ 3' },
			{ type: 'session.end', timestamp: '12:00', device: 'คิวงาน', duration_min: 290 },
			{ type: 'presence.left', timestamp: '12:05', actor: 'ผู้ควบคุม' },
		],
		interpreter: {
			name: 'ระบบควบคุมหุ่นยนต์',
			tone: 'industrial',
			map: {
				'presence.arrived': '{actor} กลับมาที่สถานี — เริ่มคิวงานต่อ',
				'presence.left': '{actor} ตัดการเชื่อมต่อ — โหมดสแตนด์บาย',
				'session.start': '{device} เริ่มทำงาน',
				'session.end': '{device} เสร็จสิ้น — {duration_min} นาที',
				anomaly: '⚠ {zone} — ตรวจพบข้อผิดพลาด',
				recovery: '{zone} — ปรับเทียบใหม่แล้ว',
				'routine.hit': '{actor} — การวินิจฉัยผ่าน',
				'routine.missed': '{actor} — เลยกำหนดวินิจฉัย',
				'cycle.complete': '{device} — ล็อตเสร็จ · {duration_min} นาที',
				'threshold.crossed': '{zone} — ถึงเกณฑ์การสึกหรอ',
			},
		},
	},
};
